name: CD - Build and Deploy Application Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-compose.yml' # Trigger on infrastructure changes
      - 'prometheus.yml'     # Trigger on infrastructure changes
      - '.github/workflows/cd.yml' # Redeploy if the deployment workflow itself changes

jobs:
  build-and-push:
    # This job runs on a standard GitHub-hosted runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This uses secrets to securely log in without exposing your credentials.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/housing-api:latest

  deploy:
      # This job depends on the 'build-and-push' job completing successfully
    needs: build-and-push
    runs-on: self-hosted # This runs on the EC2 instance

    steps:
      # Step 1: Checkout the latest code to get the new docker-compose.yml
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1.5: Kill any existing uvicorn processes that might be using port 8000
      - name: Kill existing uvicorn processes
        run: sudo pkill -f uvicorn || true

      # Step 2: Stop and remove existing containers
      - name: Stop existing containers
        run: |
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          docker-compose down || true

      # Step 3: Pull the latest API image from Docker Hub
      - name: Pull latest housing-api image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/housing-api:latest

      # Step 4: Deploy the entire stack using Docker Compose
      # This command will start fresh containers with the new image
      - name: Deploy with Docker Compose
        run: |
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          docker-compose up -d

      # Step 5: Clean up unused images to save space
      - name: Clean up unused Docker images
        run: docker image prune -f