name: CI - Lint and Test

# Trigger this workflow on every pull request to the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    # Use the standard GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest 

      # Step 4: Run the linter (flake8)
      # This checks your code for style issues and simple errors.
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Run tests with pytest
      # This will automatically discover and run any tests in your 'tests/' directory.
      # You will need to create some simple tests for this to be effective.
      - name: Test with pytest
        run: |
          pytest